### ISSUE TITLE
Trying to run on Google Colab (python 3.7.10) fails

### ISSUE THREAD

**Issue by rvencu** [goodboy/tractor#213]
at `import tractor` I am getting this:
```
/usr/local/lib/python3.7/dist-packages/tractor/_debug.py in <module>()
     24     # pdbpp is installed in regular mode...it monkey patches stuff
     25     import pdb
---> 26     assert pdb.xpm, "pdbpp is not installed?"  # type: ignore
     27     pdbpp = pdb
     28 

AttributeError: module 'pdb' has no attribute 'xpm'
```

Running `!pip install pdbpp` does not help

**Comment by goodboy** [comment]
@rvencu thanks for reporting.

This may have to do with changes in recent pdbpp?

Can you show the version you're using just for sanity check?

I'll look at their changes shortly.

**Comment by goodboy** [comment]
Hmm so the [function is still there](https://github.com/pdbpp/pdbpp/blob/master/src/pdbpp.py#L2216) but i feel like i've definitely seen this same issue before and can't remember what it was.

We would have seen it in CI if it was a blocker i'd imagine.

@rvencu what happens when you manually inspect `pdb` after import from the python repl?

**Comment by rvencu** [comment]
As I mentioned, this happens in Google Colab
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-407ef6aa9051> in <module>()
      1 import pdb
----> 2 pdb.xpm

AttributeError: module 'pdb' has no attribute 'xpm'
```

**Comment by goodboy** [comment]
Uhh ok.

We don't support anything google really; probably never will, so 🤷🏼.

I'm pretty sure I've given some good tips above for how to solve your issue.

**It's not anything to do with this project or `pdbpp`** since then we'd see the issue in our CI.
It's probably whatever proprietary, not well formed environment you're dealing with from a shoddy big tech platform.

You'll probably want to dig into how to get `pdbpp` working in that env you're using, try doing the manual import steps suggested above and then try making `tractor` work.
 
If you figure it out please feel free to report back with your tips on this issue.

**Comment by rvencu** [comment]
I solved the problem by restarting the runtime so it can see pdbpp lib after reinstalling it
