### ISSUE TITLE
Spawning a cluster of actors

### ISSUE THREAD

**Issue by xdb64** [goodboy/tractor#242]
I'm using `tractor` with my [TCP SYN port scanner](https://github.com/adder46/wrath) and I'm amazed by its smooth integration with trio, as well as the performance I've managed to squeeze out of my computer using these great libs.

During the development, I've come across the need to spawn a cluster of actors, open contexts on all of them, and then open streams on those. Currently, I have to hard-code everything (one spawn-context-stream triplet per actor) which results in a big `async with` block. I wish there was a handy utility procedure that would spawn `n` actors, open contexts on all of them, and finally, open streams - thus allowing for a number of streams proportional to the number of CPU cores to be created, for example. I'm sure what I'm asking is too specific, but I am also sure that these peculiarities could be abstracted away in a couple of generalized utility routines for doing similar tasks.

I know some of this is on its way, but in any case, please let me know once it's ready; I'd be happy to assist with battle-testing.

**Comment by goodboy** [comment]
>  I'm amazed by its smooth integration with trio, as well as the performance I've managed to squeeze out of my computer using these great libs.

😎 

@adder46 thanks for the issue friend.

I'm hoping we can get you what you need in #241 and ideally get some decent teardown latency going as well.

As mentioned in chat, the `Context.open_stream()` only really benefits from concurrency on `__aexit__()` (since it'll send a `'stop'` msg on close) so we'll need to target maybe even avoiding that bit if we want some kind of *hard shutdown* of streams.

**Comment by goodboy** [comment]
I *think* we added this in #241 yah?

**Comment by goodboy** [comment]
Closed via #241.
