### ISSUE TITLE
doctests for examples

### ISSUE THREAD

**Issue by salotz** [goodboy/tractor#98]
Implement doctests for examples in readme. Probably should just set a proper sphinx doc subtree before this.

**Comment by goodboy** [comment]
@salotz recently discovered when testing #95 that the first examples in the docs were totally broken :crying_cat_face: 

This is now fixed but we need proper doc tests that ensure the examples we write actually work.

Some options:
1. just [doctest](https://docs.python.org/3.8/library/doctest.html) (probably need this for snippets in doc strings anyway?)
1. make an `examples/` directory with modules containing example code and then run them using `pytest` and include them in sphinx docs (once we do #99) using a [`..literalinclude::` directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude)

I'm partial to 2. just because it means code as code, once, in one place, as files peeps can `wget`/`curl` and if the content changes then the docs reflect it instead of the other way around.

**Comment by goodboy** [comment]
For running examples as scripts https://github.com/kvas-it/pytest-console-scripts might also be an interesting option.

**Comment by salotz** [comment]
I am remembering now that in doctest you have to write things that looks like a command prompt. So it kind of mimics interactive usage. I don't think that is appropriate for the examples which run many lines, functions etc. So that script tester + include is the way to go.
